<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-06-23T14:36:57-04:00" hostname="https://syngentacanada--full.my.salesforce.com" tests="4" failures="1"  errors="0"  time="23.55">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="4"/>
            <property name="passing" value="3"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="75%"/>
            <property name="failRate" value="25%"/>
            <property name="testStartTime" value="Jun 23, 2020 2:36 PM"/>
            <property name="testExecutionTime" value="23.55 s"/>
            <property name="testTotalTime" value="23.55 s"/>
            <property name="commandTime" value="44.09 s"/>
            <property name="hostname" value="https://syngentacanada--full.my.salesforce.com"/>
            <property name="orgId" value="00D6300000024c2EAA"/>
            <property name="username" value="aakash.sidana@syngenta.com.full"/>
            <property name="testRunId" value="7076300001VpqC3"/>
            <property name="userId" value="0053m00000AlyrWAAR"/>
            <property name="testRunCoverage" value="81%"/>
            <property name="orgWideCoverage" value="80%"/>
        </properties>
        <testcase name="testCallout" classname="CalloutClassTest" time="0.03">
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest" time="6.95">
            <failure message="System.FinalException: Testing already started"><![CDATA[Class.System.Test.startTest: line 15, column 1
Class.Contact_TriggerTest.runTest: line 108, column 1]]></failure>
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest2" time="10.08">
        </testcase>
        <testcase name="runTest" classname="Contact_Trigger_Primary_Contact_Test" time="6.5">
        </testcase>
    </testsuite>
</testsuites>
