<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-05-27T15:39:56-04:00" hostname="https://syngentacanada--full.my.salesforce.com" tests="1" failures="1"  errors="0"  time="2.1">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="May 27, 2020 3:39 PM"/>
            <property name="testExecutionTime" value="2.1 s"/>
            <property name="testTotalTime" value="2.1 s"/>
            <property name="commandTime" value="12.54 s"/>
            <property name="hostname" value="https://syngentacanada--full.my.salesforce.com"/>
            <property name="orgId" value="00D2g0000008aPPEAY"/>
            <property name="username" value="aakash.sidana@syngenta.com.full"/>
            <property name="testRunId" value="7072g00000G8Agb"/>
            <property name="userId" value="0053m00000AlyrWAAR"/>
            <property name="testRunCoverage" value="76%"/>
            <property name="orgWideCoverage" value="74%"/>
        </properties>
        <testcase name="runTest" classname="Contact_TriggerTest2" time="2.1">
            <failure message="System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, Contact_Trigger: execution of AfterInsert

caused by: System.NullPointerException: Attempt to de-reference a null object

Trigger.Contact_Trigger: line 27, column 1: []"><![CDATA[Class.Contact_TriggerTest2.runTest: line 42, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
